// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * @returns {$CancellablePromise<[boolean, string]>}
 */
export function CloseApp() {
    return $Call.ByID(3062407203);
}

/**
 * @param {number} timeout
 * @returns {$CancellablePromise<[boolean, string]>}
 */
export function CloseAppAfterTimeout(timeout) {
    return $Call.ByID(1512946294, timeout);
}

/**
 * @returns {$CancellablePromise<[boolean, string]>}
 */
export function GetCurrentLauncherVersion() {
    return $Call.ByID(2625883531);
}

/**
 * @returns {$CancellablePromise<[boolean, string]>}
 */
export function HideApp() {
    return $Call.ByID(1725868423);
}

/**
 * @returns {$CancellablePromise<[boolean, string]>}
 */
export function MaximizeApp() {
    return $Call.ByID(1442335181);
}

/**
 * @returns {$CancellablePromise<[boolean, string]>}
 */
export function MinimizeApp() {
    return $Call.ByID(346729495);
}

/**
 * @returns {$CancellablePromise<[boolean, string]>}
 */
export function RestoreApp() {
    return $Call.ByID(3772619029);
}

/**
 * @param {number} width
 * @param {number} height
 * @returns {$CancellablePromise<[boolean, string]>}
 */
export function SetWindowSize(width, height) {
    return $Call.ByID(979032529, width, height);
}
